FROM node:lts-bullseye
SHELL ["/bin/bash", "-c"]
RUN npm -g install pnpm && SHELL=bash pnpm setup && source /root/.bashrc && pnpm add -g pnpm
RUN pnpm add typescript tslib
WORKDIR /opt/oid4vci-demo-frontend

COPY ./packages/oid4vci-demo-frontend .
RUN pnpm install -r
RUN pnpm build
WORKDIR /opt/oid4vci-demo-frontend
ENTRYPOINT ["pnpm", "start:prod"]
