FROM node:lts-bookworm
SHELL ["/bin/bash", "-c"]
RUN npm -g install pnpm && SHELL=bash pnpm setup && source /root/.bashrc && pnpm add -g pnpm
RUN pnpm add typescript tslib
WORKDIR /opt/oid4vp-demo-frontend

COPY /. .
RUN rm -rf /root/.local/share/pnpm/store
RUN pnpm install -r
RUN pnpm build
WORKDIR /opt/ssi-agent/packages/oid4vp-demo-frontend
ENTRYPOINT ["pnpm", "start:prod"]
